---
name: Kivio - Blog for DevOps
title: Kivio - Blog for DevOps
owner: rollinhand
markdown: kramdown
permalink: /blog/entry/:year/:month/:day/:title
plugins:
  - jekyll-paginate
  - jekyll-avatar
  - jekyll-sitemap
sass:
  style: compressed  

paginate: 6
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
include: ["_pages"]

collections:
    category:
        output: true

defaults:
    -
        scope: 
            path: ""
            type: category
        values:
            layout: "category"    
---
